// Generated by gencpp from file graspit_interface/ApproachToContact.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_APPROACHTOCONTACT_H
#define GRASPIT_INTERFACE_MESSAGE_APPROACHTOCONTACT_H

#include <ros/service_traits.h>


#include <graspit_interface/ApproachToContactRequest.h>
#include <graspit_interface/ApproachToContactResponse.h>


namespace graspit_interface
{

struct ApproachToContact
{

typedef ApproachToContactRequest Request;
typedef ApproachToContactResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ApproachToContact
} // namespace graspit_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graspit_interface::ApproachToContact > {
  static const char* value()
  {
    return "8bedd9e6f36adf22b7fa2df39c3f07e2";
  }

  static const char* value(const ::graspit_interface::ApproachToContact&) { return value(); }
};

template<>
struct DataType< ::graspit_interface::ApproachToContact > {
  static const char* value()
  {
    return "graspit_interface/ApproachToContact";
  }

  static const char* value(const ::graspit_interface::ApproachToContact&) { return value(); }
};


// service_traits::MD5Sum< ::graspit_interface::ApproachToContactRequest> should match 
// service_traits::MD5Sum< ::graspit_interface::ApproachToContact > 
template<>
struct MD5Sum< ::graspit_interface::ApproachToContactRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_interface::ApproachToContact >::value();
  }
  static const char* value(const ::graspit_interface::ApproachToContactRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_interface::ApproachToContactRequest> should match 
// service_traits::DataType< ::graspit_interface::ApproachToContact > 
template<>
struct DataType< ::graspit_interface::ApproachToContactRequest>
{
  static const char* value()
  {
    return DataType< ::graspit_interface::ApproachToContact >::value();
  }
  static const char* value(const ::graspit_interface::ApproachToContactRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graspit_interface::ApproachToContactResponse> should match 
// service_traits::MD5Sum< ::graspit_interface::ApproachToContact > 
template<>
struct MD5Sum< ::graspit_interface::ApproachToContactResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_interface::ApproachToContact >::value();
  }
  static const char* value(const ::graspit_interface::ApproachToContactResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_interface::ApproachToContactResponse> should match 
// service_traits::DataType< ::graspit_interface::ApproachToContact > 
template<>
struct DataType< ::graspit_interface::ApproachToContactResponse>
{
  static const char* value()
  {
    return DataType< ::graspit_interface::ApproachToContact >::value();
  }
  static const char* value(const ::graspit_interface::ApproachToContactResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_APPROACHTOCONTACT_H
