// Generated by gencpp from file graspit_interface/AutoGrasp.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_AUTOGRASP_H
#define GRASPIT_INTERFACE_MESSAGE_AUTOGRASP_H

#include <ros/service_traits.h>


#include <graspit_interface/AutoGraspRequest.h>
#include <graspit_interface/AutoGraspResponse.h>


namespace graspit_interface
{

struct AutoGrasp
{

typedef AutoGraspRequest Request;
typedef AutoGraspResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AutoGrasp
} // namespace graspit_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graspit_interface::AutoGrasp > {
  static const char* value()
  {
    return "cbd9d726d191ae6a9b05b66d9cffaf54";
  }

  static const char* value(const ::graspit_interface::AutoGrasp&) { return value(); }
};

template<>
struct DataType< ::graspit_interface::AutoGrasp > {
  static const char* value()
  {
    return "graspit_interface/AutoGrasp";
  }

  static const char* value(const ::graspit_interface::AutoGrasp&) { return value(); }
};


// service_traits::MD5Sum< ::graspit_interface::AutoGraspRequest> should match 
// service_traits::MD5Sum< ::graspit_interface::AutoGrasp > 
template<>
struct MD5Sum< ::graspit_interface::AutoGraspRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_interface::AutoGrasp >::value();
  }
  static const char* value(const ::graspit_interface::AutoGraspRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_interface::AutoGraspRequest> should match 
// service_traits::DataType< ::graspit_interface::AutoGrasp > 
template<>
struct DataType< ::graspit_interface::AutoGraspRequest>
{
  static const char* value()
  {
    return DataType< ::graspit_interface::AutoGrasp >::value();
  }
  static const char* value(const ::graspit_interface::AutoGraspRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graspit_interface::AutoGraspResponse> should match 
// service_traits::MD5Sum< ::graspit_interface::AutoGrasp > 
template<>
struct MD5Sum< ::graspit_interface::AutoGraspResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_interface::AutoGrasp >::value();
  }
  static const char* value(const ::graspit_interface::AutoGraspResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_interface::AutoGraspResponse> should match 
// service_traits::DataType< ::graspit_interface::AutoGrasp > 
template<>
struct DataType< ::graspit_interface::AutoGraspResponse>
{
  static const char* value()
  {
    return DataType< ::graspit_interface::AutoGrasp >::value();
  }
  static const char* value(const ::graspit_interface::AutoGraspResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_AUTOGRASP_H
