// Generated by gencpp from file graspit_interface/ComputeEnergy.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_COMPUTEENERGY_H
#define GRASPIT_INTERFACE_MESSAGE_COMPUTEENERGY_H

#include <ros/service_traits.h>


#include <graspit_interface/ComputeEnergyRequest.h>
#include <graspit_interface/ComputeEnergyResponse.h>


namespace graspit_interface
{

struct ComputeEnergy
{

typedef ComputeEnergyRequest Request;
typedef ComputeEnergyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ComputeEnergy
} // namespace graspit_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graspit_interface::ComputeEnergy > {
  static const char* value()
  {
    return "dfcebf964a22ec5ff63ce7a982066d70";
  }

  static const char* value(const ::graspit_interface::ComputeEnergy&) { return value(); }
};

template<>
struct DataType< ::graspit_interface::ComputeEnergy > {
  static const char* value()
  {
    return "graspit_interface/ComputeEnergy";
  }

  static const char* value(const ::graspit_interface::ComputeEnergy&) { return value(); }
};


// service_traits::MD5Sum< ::graspit_interface::ComputeEnergyRequest> should match 
// service_traits::MD5Sum< ::graspit_interface::ComputeEnergy > 
template<>
struct MD5Sum< ::graspit_interface::ComputeEnergyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_interface::ComputeEnergy >::value();
  }
  static const char* value(const ::graspit_interface::ComputeEnergyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_interface::ComputeEnergyRequest> should match 
// service_traits::DataType< ::graspit_interface::ComputeEnergy > 
template<>
struct DataType< ::graspit_interface::ComputeEnergyRequest>
{
  static const char* value()
  {
    return DataType< ::graspit_interface::ComputeEnergy >::value();
  }
  static const char* value(const ::graspit_interface::ComputeEnergyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graspit_interface::ComputeEnergyResponse> should match 
// service_traits::MD5Sum< ::graspit_interface::ComputeEnergy > 
template<>
struct MD5Sum< ::graspit_interface::ComputeEnergyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_interface::ComputeEnergy >::value();
  }
  static const char* value(const ::graspit_interface::ComputeEnergyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_interface::ComputeEnergyResponse> should match 
// service_traits::DataType< ::graspit_interface::ComputeEnergy > 
template<>
struct DataType< ::graspit_interface::ComputeEnergyResponse>
{
  static const char* value()
  {
    return DataType< ::graspit_interface::ComputeEnergy >::value();
  }
  static const char* value(const ::graspit_interface::ComputeEnergyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_COMPUTEENERGY_H
