// Generated by gencpp from file graspit_interface/DynamicAutoGraspCompleteRequest.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_DYNAMICAUTOGRASPCOMPLETEREQUEST_H
#define GRASPIT_INTERFACE_MESSAGE_DYNAMICAUTOGRASPCOMPLETEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graspit_interface
{
template <class ContainerAllocator>
struct DynamicAutoGraspCompleteRequest_
{
  typedef DynamicAutoGraspCompleteRequest_<ContainerAllocator> Type;

  DynamicAutoGraspCompleteRequest_()
    : id(0)  {
    }
  DynamicAutoGraspCompleteRequest_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DynamicAutoGraspCompleteRequest_

typedef ::graspit_interface::DynamicAutoGraspCompleteRequest_<std::allocator<void> > DynamicAutoGraspCompleteRequest;

typedef boost::shared_ptr< ::graspit_interface::DynamicAutoGraspCompleteRequest > DynamicAutoGraspCompleteRequestPtr;
typedef boost::shared_ptr< ::graspit_interface::DynamicAutoGraspCompleteRequest const> DynamicAutoGraspCompleteRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace graspit_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'graspit_interface': ['/home/mamad/Graspit/src/graspit_interface/msg', '/home/mamad/Graspit/devel/share/graspit_interface/msg'], 'actionlib': ['/opt/ros/kinetic/share/actionlib/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "309d4b30834b338cced19e5622a97a03";
  }

  static const char* value(const ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x309d4b30834b338cULL;
  static const uint64_t static_value2 = 0xced19e5622a97a03ULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_interface/DynamicAutoGraspCompleteRequest";
  }

  static const char* value(const ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n\
";
  }

  static const char* value(const ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DynamicAutoGraspCompleteRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_interface::DynamicAutoGraspCompleteRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_DYNAMICAUTOGRASPCOMPLETEREQUEST_H
