// Generated by gencpp from file graspit_interface/GetBodies.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_GETBODIES_H
#define GRASPIT_INTERFACE_MESSAGE_GETBODIES_H

#include <ros/service_traits.h>


#include <graspit_interface/GetBodiesRequest.h>
#include <graspit_interface/GetBodiesResponse.h>


namespace graspit_interface
{

struct GetBodies
{

typedef GetBodiesRequest Request;
typedef GetBodiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBodies
} // namespace graspit_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graspit_interface::GetBodies > {
  static const char* value()
  {
    return "4f22efebf407aadba2ecc69df353d113";
  }

  static const char* value(const ::graspit_interface::GetBodies&) { return value(); }
};

template<>
struct DataType< ::graspit_interface::GetBodies > {
  static const char* value()
  {
    return "graspit_interface/GetBodies";
  }

  static const char* value(const ::graspit_interface::GetBodies&) { return value(); }
};


// service_traits::MD5Sum< ::graspit_interface::GetBodiesRequest> should match 
// service_traits::MD5Sum< ::graspit_interface::GetBodies > 
template<>
struct MD5Sum< ::graspit_interface::GetBodiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_interface::GetBodies >::value();
  }
  static const char* value(const ::graspit_interface::GetBodiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_interface::GetBodiesRequest> should match 
// service_traits::DataType< ::graspit_interface::GetBodies > 
template<>
struct DataType< ::graspit_interface::GetBodiesRequest>
{
  static const char* value()
  {
    return DataType< ::graspit_interface::GetBodies >::value();
  }
  static const char* value(const ::graspit_interface::GetBodiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graspit_interface::GetBodiesResponse> should match 
// service_traits::MD5Sum< ::graspit_interface::GetBodies > 
template<>
struct MD5Sum< ::graspit_interface::GetBodiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_interface::GetBodies >::value();
  }
  static const char* value(const ::graspit_interface::GetBodiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_interface::GetBodiesResponse> should match 
// service_traits::DataType< ::graspit_interface::GetBodies > 
template<>
struct DataType< ::graspit_interface::GetBodiesResponse>
{
  static const char* value()
  {
    return DataType< ::graspit_interface::GetBodies >::value();
  }
  static const char* value(const ::graspit_interface::GetBodiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_GETBODIES_H
