// Generated by gencpp from file graspit_interface/GetGraspableBodies.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_GETGRASPABLEBODIES_H
#define GRASPIT_INTERFACE_MESSAGE_GETGRASPABLEBODIES_H

#include <ros/service_traits.h>


#include <graspit_interface/GetGraspableBodiesRequest.h>
#include <graspit_interface/GetGraspableBodiesResponse.h>


namespace graspit_interface
{

struct GetGraspableBodies
{

typedef GetGraspableBodiesRequest Request;
typedef GetGraspableBodiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGraspableBodies
} // namespace graspit_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graspit_interface::GetGraspableBodies > {
  static const char* value()
  {
    return "4f22efebf407aadba2ecc69df353d113";
  }

  static const char* value(const ::graspit_interface::GetGraspableBodies&) { return value(); }
};

template<>
struct DataType< ::graspit_interface::GetGraspableBodies > {
  static const char* value()
  {
    return "graspit_interface/GetGraspableBodies";
  }

  static const char* value(const ::graspit_interface::GetGraspableBodies&) { return value(); }
};


// service_traits::MD5Sum< ::graspit_interface::GetGraspableBodiesRequest> should match 
// service_traits::MD5Sum< ::graspit_interface::GetGraspableBodies > 
template<>
struct MD5Sum< ::graspit_interface::GetGraspableBodiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_interface::GetGraspableBodies >::value();
  }
  static const char* value(const ::graspit_interface::GetGraspableBodiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_interface::GetGraspableBodiesRequest> should match 
// service_traits::DataType< ::graspit_interface::GetGraspableBodies > 
template<>
struct DataType< ::graspit_interface::GetGraspableBodiesRequest>
{
  static const char* value()
  {
    return DataType< ::graspit_interface::GetGraspableBodies >::value();
  }
  static const char* value(const ::graspit_interface::GetGraspableBodiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graspit_interface::GetGraspableBodiesResponse> should match 
// service_traits::MD5Sum< ::graspit_interface::GetGraspableBodies > 
template<>
struct MD5Sum< ::graspit_interface::GetGraspableBodiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_interface::GetGraspableBodies >::value();
  }
  static const char* value(const ::graspit_interface::GetGraspableBodiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_interface::GetGraspableBodiesResponse> should match 
// service_traits::DataType< ::graspit_interface::GetGraspableBodies > 
template<>
struct DataType< ::graspit_interface::GetGraspableBodiesResponse>
{
  static const char* value()
  {
    return DataType< ::graspit_interface::GetGraspableBodies >::value();
  }
  static const char* value(const ::graspit_interface::GetGraspableBodiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_GETGRASPABLEBODIES_H
