// Generated by gencpp from file graspit_interface/LoadWorld.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_LOADWORLD_H
#define GRASPIT_INTERFACE_MESSAGE_LOADWORLD_H

#include <ros/service_traits.h>


#include <graspit_interface/LoadWorldRequest.h>
#include <graspit_interface/LoadWorldResponse.h>


namespace graspit_interface
{

struct LoadWorld
{

typedef LoadWorldRequest Request;
typedef LoadWorldResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadWorld
} // namespace graspit_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graspit_interface::LoadWorld > {
  static const char* value()
  {
    return "285e9fabd629899a63d0043517ce4bae";
  }

  static const char* value(const ::graspit_interface::LoadWorld&) { return value(); }
};

template<>
struct DataType< ::graspit_interface::LoadWorld > {
  static const char* value()
  {
    return "graspit_interface/LoadWorld";
  }

  static const char* value(const ::graspit_interface::LoadWorld&) { return value(); }
};


// service_traits::MD5Sum< ::graspit_interface::LoadWorldRequest> should match 
// service_traits::MD5Sum< ::graspit_interface::LoadWorld > 
template<>
struct MD5Sum< ::graspit_interface::LoadWorldRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_interface::LoadWorld >::value();
  }
  static const char* value(const ::graspit_interface::LoadWorldRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_interface::LoadWorldRequest> should match 
// service_traits::DataType< ::graspit_interface::LoadWorld > 
template<>
struct DataType< ::graspit_interface::LoadWorldRequest>
{
  static const char* value()
  {
    return DataType< ::graspit_interface::LoadWorld >::value();
  }
  static const char* value(const ::graspit_interface::LoadWorldRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graspit_interface::LoadWorldResponse> should match 
// service_traits::MD5Sum< ::graspit_interface::LoadWorld > 
template<>
struct MD5Sum< ::graspit_interface::LoadWorldResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_interface::LoadWorld >::value();
  }
  static const char* value(const ::graspit_interface::LoadWorldResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_interface::LoadWorldResponse> should match 
// service_traits::DataType< ::graspit_interface::LoadWorld > 
template<>
struct DataType< ::graspit_interface::LoadWorldResponse>
{
  static const char* value()
  {
    return DataType< ::graspit_interface::LoadWorld >::value();
  }
  static const char* value(const ::graspit_interface::LoadWorldResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_LOADWORLD_H
