// Generated by gencpp from file graspit_interface/SetRobotDesiredDOFRequest.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_SETROBOTDESIREDDOFREQUEST_H
#define GRASPIT_INTERFACE_MESSAGE_SETROBOTDESIREDDOFREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graspit_interface
{
template <class ContainerAllocator>
struct SetRobotDesiredDOFRequest_
{
  typedef SetRobotDesiredDOFRequest_<ContainerAllocator> Type;

  SetRobotDesiredDOFRequest_()
    : id(0)
    , dofs()
    , dof_velocities()  {
    }
  SetRobotDesiredDOFRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , dofs(_alloc)
    , dof_velocities(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _dofs_type;
  _dofs_type dofs;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _dof_velocities_type;
  _dof_velocities_type dof_velocities;





  typedef boost::shared_ptr< ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRobotDesiredDOFRequest_

typedef ::graspit_interface::SetRobotDesiredDOFRequest_<std::allocator<void> > SetRobotDesiredDOFRequest;

typedef boost::shared_ptr< ::graspit_interface::SetRobotDesiredDOFRequest > SetRobotDesiredDOFRequestPtr;
typedef boost::shared_ptr< ::graspit_interface::SetRobotDesiredDOFRequest const> SetRobotDesiredDOFRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace graspit_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'graspit_interface': ['/home/mamad/Graspit/src/graspit_interface/msg', '/home/mamad/Graspit/devel/share/graspit_interface/msg'], 'actionlib': ['/opt/ros/kinetic/share/actionlib/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69456a29060bcb953b1cabeb2c68b83a";
  }

  static const char* value(const ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69456a29060bcb95ULL;
  static const uint64_t static_value2 = 0x3b1cabeb2c68b83aULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_interface/SetRobotDesiredDOFRequest";
  }

  static const char* value(const ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n\
float64[] dofs\n\
float64[] dof_velocities\n\
";
  }

  static const char* value(const ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.dofs);
      stream.next(m.dof_velocities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRobotDesiredDOFRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_interface::SetRobotDesiredDOFRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "dofs[]" << std::endl;
    for (size_t i = 0; i < v.dofs.size(); ++i)
    {
      s << indent << "  dofs[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.dofs[i]);
    }
    s << indent << "dof_velocities[]" << std::endl;
    for (size_t i = 0; i < v.dof_velocities.size(); ++i)
    {
      s << indent << "  dof_velocities[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.dof_velocities[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_SETROBOTDESIREDDOFREQUEST_H
