// Generated by gencpp from file graspit_interface/ToggleAllCollisions.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_TOGGLEALLCOLLISIONS_H
#define GRASPIT_INTERFACE_MESSAGE_TOGGLEALLCOLLISIONS_H

#include <ros/service_traits.h>


#include <graspit_interface/ToggleAllCollisionsRequest.h>
#include <graspit_interface/ToggleAllCollisionsResponse.h>


namespace graspit_interface
{

struct ToggleAllCollisions
{

typedef ToggleAllCollisionsRequest Request;
typedef ToggleAllCollisionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToggleAllCollisions
} // namespace graspit_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graspit_interface::ToggleAllCollisions > {
  static const char* value()
  {
    return "9c8e2540904142e4bddf9c31767c9e80";
  }

  static const char* value(const ::graspit_interface::ToggleAllCollisions&) { return value(); }
};

template<>
struct DataType< ::graspit_interface::ToggleAllCollisions > {
  static const char* value()
  {
    return "graspit_interface/ToggleAllCollisions";
  }

  static const char* value(const ::graspit_interface::ToggleAllCollisions&) { return value(); }
};


// service_traits::MD5Sum< ::graspit_interface::ToggleAllCollisionsRequest> should match 
// service_traits::MD5Sum< ::graspit_interface::ToggleAllCollisions > 
template<>
struct MD5Sum< ::graspit_interface::ToggleAllCollisionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_interface::ToggleAllCollisions >::value();
  }
  static const char* value(const ::graspit_interface::ToggleAllCollisionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_interface::ToggleAllCollisionsRequest> should match 
// service_traits::DataType< ::graspit_interface::ToggleAllCollisions > 
template<>
struct DataType< ::graspit_interface::ToggleAllCollisionsRequest>
{
  static const char* value()
  {
    return DataType< ::graspit_interface::ToggleAllCollisions >::value();
  }
  static const char* value(const ::graspit_interface::ToggleAllCollisionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graspit_interface::ToggleAllCollisionsResponse> should match 
// service_traits::MD5Sum< ::graspit_interface::ToggleAllCollisions > 
template<>
struct MD5Sum< ::graspit_interface::ToggleAllCollisionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_interface::ToggleAllCollisions >::value();
  }
  static const char* value(const ::graspit_interface::ToggleAllCollisionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_interface::ToggleAllCollisionsResponse> should match 
// service_traits::DataType< ::graspit_interface::ToggleAllCollisions > 
template<>
struct DataType< ::graspit_interface::ToggleAllCollisionsResponse>
{
  static const char* value()
  {
    return DataType< ::graspit_interface::ToggleAllCollisions >::value();
  }
  static const char* value(const ::graspit_interface::ToggleAllCollisionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_TOGGLEALLCOLLISIONS_H
