// Generated by gencpp from file grasp_planning_graspit_msgs/AddToDatabaseRequest.msg
// DO NOT EDIT!


#ifndef GRASP_PLANNING_GRASPIT_MSGS_MESSAGE_ADDTODATABASEREQUEST_H
#define GRASP_PLANNING_GRASPIT_MSGS_MESSAGE_ADDTODATABASEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grasp_planning_graspit_msgs
{
template <class ContainerAllocator>
struct AddToDatabaseRequest_
{
  typedef AddToDatabaseRequest_<ContainerAllocator> Type;

  AddToDatabaseRequest_()
    : filename()
    , isRobot(false)
    , asGraspable(false)
    , modelName()
    , jointNames()  {
    }
  AddToDatabaseRequest_(const ContainerAllocator& _alloc)
    : filename(_alloc)
    , isRobot(false)
    , asGraspable(false)
    , modelName(_alloc)
    , jointNames(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filename_type;
  _filename_type filename;

   typedef uint8_t _isRobot_type;
  _isRobot_type isRobot;

   typedef uint8_t _asGraspable_type;
  _asGraspable_type asGraspable;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _modelName_type;
  _modelName_type modelName;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _jointNames_type;
  _jointNames_type jointNames;





  typedef boost::shared_ptr< ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddToDatabaseRequest_

typedef ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<std::allocator<void> > AddToDatabaseRequest;

typedef boost::shared_ptr< ::grasp_planning_graspit_msgs::AddToDatabaseRequest > AddToDatabaseRequestPtr;
typedef boost::shared_ptr< ::grasp_planning_graspit_msgs::AddToDatabaseRequest const> AddToDatabaseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace grasp_planning_graspit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ab6c9f30acc0ca8b3199d205c07915a";
  }

  static const char* value(const ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ab6c9f30acc0ca8ULL;
  static const uint64_t static_value2 = 0xb3199d205c07915aULL;
};

template<class ContainerAllocator>
struct DataType< ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasp_planning_graspit_msgs/AddToDatabaseRequest";
  }

  static const char* value(const ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
string filename\n\
\n\
\n\
bool isRobot\n\
\n\
\n\
\n\
bool asGraspable\n\
\n\
\n\
\n\
\n\
string modelName\n\
\n\
\n\
\n\
string[] jointNames\n\
\n\
";
  }

  static const char* value(const ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.filename);
      stream.next(m.isRobot);
      stream.next(m.asGraspable);
      stream.next(m.modelName);
      stream.next(m.jointNames);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddToDatabaseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasp_planning_graspit_msgs::AddToDatabaseRequest_<ContainerAllocator>& v)
  {
    s << indent << "filename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.filename);
    s << indent << "isRobot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isRobot);
    s << indent << "asGraspable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.asGraspable);
    s << indent << "modelName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.modelName);
    s << indent << "jointNames[]" << std::endl;
    for (size_t i = 0; i < v.jointNames.size(); ++i)
    {
      s << indent << "  jointNames[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.jointNames[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASP_PLANNING_GRASPIT_MSGS_MESSAGE_ADDTODATABASEREQUEST_H
