// Generated by gencpp from file grasp_planning_graspit_msgs/AddToDatabase.msg
// DO NOT EDIT!


#ifndef GRASP_PLANNING_GRASPIT_MSGS_MESSAGE_ADDTODATABASE_H
#define GRASP_PLANNING_GRASPIT_MSGS_MESSAGE_ADDTODATABASE_H

#include <ros/service_traits.h>


#include <grasp_planning_graspit_msgs/AddToDatabaseRequest.h>
#include <grasp_planning_graspit_msgs/AddToDatabaseResponse.h>


namespace grasp_planning_graspit_msgs
{

struct AddToDatabase
{

typedef AddToDatabaseRequest Request;
typedef AddToDatabaseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddToDatabase
} // namespace grasp_planning_graspit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grasp_planning_graspit_msgs::AddToDatabase > {
  static const char* value()
  {
    return "1d861bc118bc160b1e8a75f648c6112e";
  }

  static const char* value(const ::grasp_planning_graspit_msgs::AddToDatabase&) { return value(); }
};

template<>
struct DataType< ::grasp_planning_graspit_msgs::AddToDatabase > {
  static const char* value()
  {
    return "grasp_planning_graspit_msgs/AddToDatabase";
  }

  static const char* value(const ::grasp_planning_graspit_msgs::AddToDatabase&) { return value(); }
};


// service_traits::MD5Sum< ::grasp_planning_graspit_msgs::AddToDatabaseRequest> should match 
// service_traits::MD5Sum< ::grasp_planning_graspit_msgs::AddToDatabase > 
template<>
struct MD5Sum< ::grasp_planning_graspit_msgs::AddToDatabaseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grasp_planning_graspit_msgs::AddToDatabase >::value();
  }
  static const char* value(const ::grasp_planning_graspit_msgs::AddToDatabaseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grasp_planning_graspit_msgs::AddToDatabaseRequest> should match 
// service_traits::DataType< ::grasp_planning_graspit_msgs::AddToDatabase > 
template<>
struct DataType< ::grasp_planning_graspit_msgs::AddToDatabaseRequest>
{
  static const char* value()
  {
    return DataType< ::grasp_planning_graspit_msgs::AddToDatabase >::value();
  }
  static const char* value(const ::grasp_planning_graspit_msgs::AddToDatabaseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grasp_planning_graspit_msgs::AddToDatabaseResponse> should match 
// service_traits::MD5Sum< ::grasp_planning_graspit_msgs::AddToDatabase > 
template<>
struct MD5Sum< ::grasp_planning_graspit_msgs::AddToDatabaseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grasp_planning_graspit_msgs::AddToDatabase >::value();
  }
  static const char* value(const ::grasp_planning_graspit_msgs::AddToDatabaseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grasp_planning_graspit_msgs::AddToDatabaseResponse> should match 
// service_traits::DataType< ::grasp_planning_graspit_msgs::AddToDatabase > 
template<>
struct DataType< ::grasp_planning_graspit_msgs::AddToDatabaseResponse>
{
  static const char* value()
  {
    return DataType< ::grasp_planning_graspit_msgs::AddToDatabase >::value();
  }
  static const char* value(const ::grasp_planning_graspit_msgs::AddToDatabaseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASP_PLANNING_GRASPIT_MSGS_MESSAGE_ADDTODATABASE_H
