// Auto-generated. Do not edit!

// (in-package graspit_interface.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let PlanGraspsGoal = require('./PlanGraspsGoal.js');
let actionlib_msgs = _finder('actionlib_msgs');
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class PlanGraspsActionGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.header = null;
      this.goal_id = null;
      this.goal = null;
    }
    else {
      if (initObj.hasOwnProperty('header')) {
        this.header = initObj.header
      }
      else {
        this.header = new std_msgs.msg.Header();
      }
      if (initObj.hasOwnProperty('goal_id')) {
        this.goal_id = initObj.goal_id
      }
      else {
        this.goal_id = new actionlib_msgs.msg.GoalID();
      }
      if (initObj.hasOwnProperty('goal')) {
        this.goal = initObj.goal
      }
      else {
        this.goal = new PlanGraspsGoal();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PlanGraspsActionGoal
    // Serialize message field [header]
    bufferOffset = std_msgs.msg.Header.serialize(obj.header, buffer, bufferOffset);
    // Serialize message field [goal_id]
    bufferOffset = actionlib_msgs.msg.GoalID.serialize(obj.goal_id, buffer, bufferOffset);
    // Serialize message field [goal]
    bufferOffset = PlanGraspsGoal.serialize(obj.goal, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PlanGraspsActionGoal
    let len;
    let data = new PlanGraspsActionGoal(null);
    // Deserialize message field [header]
    data.header = std_msgs.msg.Header.deserialize(buffer, bufferOffset);
    // Deserialize message field [goal_id]
    data.goal_id = actionlib_msgs.msg.GoalID.deserialize(buffer, bufferOffset);
    // Deserialize message field [goal]
    data.goal = PlanGraspsGoal.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += std_msgs.msg.Header.getMessageSize(object.header);
    length += actionlib_msgs.msg.GoalID.getMessageSize(object.goal_id);
    length += PlanGraspsGoal.getMessageSize(object.goal);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'graspit_interface/PlanGraspsActionGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b10b6a88ddea4a4579b092e6c787f844';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    PlanGraspsGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: graspit_interface/PlanGraspsGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    int32 graspable_body_id
    
    Planner planner
    string search_energy
    SearchSpace search_space
    SearchContact search_contact
    SimAnnParams sim_ann_params
    
    int32 max_steps
    int32 feedback_num_steps
    
    ================================================================================
    MSG: graspit_interface/Planner
    uint8 SIM_ANN                      = 0
    uint8 MULTI_THREADED               = 1
    
    uint8 type
    ================================================================================
    MSG: graspit_interface/SearchSpace
    uint8 SPACE_AXIS_ANGLE    = 0
    uint8 SPACE_COMPLETE      = 1
    uint8 SPACE_ELLIPSOID     = 2
    uint8 SPACE_APPROACH      = 3
    
    uint8 type
    ================================================================================
    MSG: graspit_interface/SearchContact
    uint8 CONTACT_PRESET    = 0
    uint8 CONTACT_LIVE      = 1
    
    uint8 type	
    ================================================================================
    MSG: graspit_interface/SimAnnParams
    
    # flag to switch to custom params defined in this message. If not set, GraspIt's default settings are kept
    bool set_custom_params
    
    
    # //Annealing parameters
    # //! Annealing constant for neighbor generation schedule
    float64 YC	 	#	GraspIt! default: 7.0
    # //! Annealing constant for error acceptance schedule
    float64 HC	 	#	GraspIt! default: 7.0
    # //! Number of dimensions for neighbor generation schedule
    float64 YDIMS	#	GraspIt! default: 8.0
    # //! Number of dimensions for error acceptance schedule
    float64 HDIMS	#	GraspIt! default: 8.0
    # //! Adjust factor for neighbor generation schedule
    float64 NBR_ADJ	#	GraspIt! default: 1.0
    # //! Adjust raw errors reported by states to be in the relevant range of the annealing schedule
    float64 ERR_ADJ	#	GraspIt! default: 1.0e-6
    # //! Starting temperatue
    float64 DEF_T0	#	GraspIt! default: 1e6
    # //! Starting step
    float64 DEF_K0	#	GraspIt! default: 30000
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PlanGraspsActionGoal(null);
    if (msg.header !== undefined) {
      resolved.header = std_msgs.msg.Header.Resolve(msg.header)
    }
    else {
      resolved.header = new std_msgs.msg.Header()
    }

    if (msg.goal_id !== undefined) {
      resolved.goal_id = actionlib_msgs.msg.GoalID.Resolve(msg.goal_id)
    }
    else {
      resolved.goal_id = new actionlib_msgs.msg.GoalID()
    }

    if (msg.goal !== undefined) {
      resolved.goal = PlanGraspsGoal.Resolve(msg.goal)
    }
    else {
      resolved.goal = new PlanGraspsGoal()
    }

    return resolved;
    }
};

module.exports = PlanGraspsActionGoal;
