# PID values to use for JointControlLocalImpl

<your_robot_name>:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  <joint_name>_position_controller:
    type: position_controllers/JointPositionController
    joint: <joint_name> 
    pid: {p: 20, i: 1.0, d: 0}
  ...

  # Velocity Controllers ---------------------------------------
  <joint_name>_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: <joint_name> 
    pid: {p: 0.4, i: 0, d: 0}  
    ...
